name = "a0b_atsam3x8e_usart"
description = "A0B ATSAM3X8E USART"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "usart", "spi", "atsam3x8e", "arduino", "due"]

project-files = ["gnat/a0b_atsam3x8e_usart.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_spi = "*"
a0b_svd_atsam3x8e = "*"
